spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 5555
  address: 0.0.0.0

eureka:
  client:
    service-url:
      defaultZone: http://cakecandy-eureka-server-production.up.railway.app/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: api-gateway
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
